#!/usr/bin/env python3
"""loop12 dream.py - orchestrator of one Dreaming-Loop beat.

The Dreaming Loop is the META-loop: it reads the dated log entries and
progress files the other loops left behind, finds a failure or correction
that appears MORE THAN ONCE, and proposes the smallest possible change to the
SHARED rules (plus one deletion). It never changes the rules itself.

One beat, end to end:

    heartbeat -> clean-tree guard -> deterministic scan.py proves repeats
    (the ring that never lies) -> snapshot the repo at HEAD -> DREAMER
    (fresh headless claude) drafts the smallest rule/skill improvement +
    one deletion, citing real records -> CHECKER (fresh headless claude)
    re-derives every citation -> on PASS the proposal is committed to a local
    claude/dream-<run> branch ONLY (never main, never pushed) -> dreaming
    state advances -> the beat prints the exact git push + gh pr create
    one-liner for a human.

Nothing in the rules changes without a Pull Request and a human merge: the
engine never commits to main (it leaves the loop12 bookkeeping uncommitted
and prints the commit command), and the rule change exists only on the
claude/dream-<run> branch.

Usage (canonical interpreter: C:\\Python314\\python.exe; run from repo root):
    python loop12/dream.py --init
    python loop12/dream.py --date 2026-09-03   # one dreaming beat
    python loop12/dream.py --check             # run the scan only (no agents)
    python loop12/dream.py --show              # print the dreaming state
    python loop12/dream.py --reset             # clear NEEDS_HUMAN
"""

from __future__ import annotations

import argparse
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
from datetime import date as _date
from pathlib import Path

LOOP12 = Path(__file__).resolve().parent
LOOPPROJECTS = LOOP12.parent
try:
    REPO_ROOT = Path(subprocess.run(
        ["git", "-C", str(LOOP12), "rev-parse", "--show-toplevel"],
        capture_output=True, text=True).stdout.strip())
    if not REPO_ROOT.exists():
        raise ValueError
except Exception:
    REPO_ROOT = LOOP12.parents[2]

LOOP12_REL = str(LOOP12.relative_to(REPO_ROOT)).replace("\\", "/")   # .../loop12
SKILLS_DIR = REPO_ROOT / "loop-practice" / "loopprojects" / "skills"
SKILLS_REL = "loop-practice/loopprojects/skills"

STATE_MD = LOOP12 / "dreaming-state.md"
LOG_MD = LOOP12 / "loop-log.md"
PROGRESS_MD = LOOP12 / "progress.md"
COST_MD = LOOP12 / "cost.md"
USAGE_CSV = LOOP12 / "usage.csv"
RUNS_DIR = LOOP12 / "runs"
OBSERVED = LOOP12 / "observed-runs.md"
SCAN_PY = LOOP12 / "scan.py"
BEATS_DIR = LOOP12 / ".loop12-beats"      # git-ignored trusted snapshot root

MAX_ATTEMPTS = 2
COMMIT_TRAILER = "\nCo-Authored-By: Claude Code <noreply@anthropic.com>"
ENV = dict(os.environ)
ENV["CLAUDE_CODE_DISABLE_UNKNOWN_MODEL_WINDOW_ENFORCEMENT"] = "1"
ENV["CLAUDE_CODE_MAX_CONTEXT_TOKENS"] = "200000"

# --------------------------------------------------------------------------- #
# state (dreaming-state.md is the single source of truth)
# --------------------------------------------------------------------------- #

HEADER_RE = re.compile(r"^- \*\*(?P<key>[a-z_]+):\*\* (?P<val>.*)$")
LEDGER_ROW_RE = re.compile(r"^\| (\d+) \| (\d{4}-\d{2}-\d{2}) \| (\w+) \| "
                           r"([^ |]+) \| (.*) \|$")

STATE_DEFAULTS = {
    "state": "IDLE",          # IDLE | PROPOSED | NEEDS_HUMAN
    "run": 0,
    "last_dream": "2026-09-02",
    "branch": "—",
    "proposal": "—",
    "needs_human_note": "",
}

PROSE = """## What a dreaming beat is

A fresh engine reads the dated log entries and `progress.md` files the loops
left behind since `last_dream`, a deterministic scanner proves which
failure/correction signatures appear more than once, a **Dreamer** drafts the
smallest rule/skill improvement plus one deletion (both from the shared
`loopprojects/skills/` corpus), a **Checker** re-derives every citation, and
only on PASS the proposal is committed to a local `claude/dream-<run>` branch.
`last_dream` advances to today at the end of every completed beat.

_This file is generated by `dream.py` from its own state; do not hand-edit.
Rule changes never happen here - they live on a `claude/dream-<run>` branch
awaiting a human merge._"""


def read_state() -> dict:
    st = dict(STATE_DEFAULTS)          # parsed header values overwrite these
    st["ledger"] = []
    if STATE_MD.exists():
        for line in STATE_MD.read_text(encoding="utf-8").splitlines():
            m = HEADER_RE.match(line)
            if m:
                st[m.group("key")] = m.group("val")
            m2 = LEDGER_ROW_RE.match(line)
            if m2:
                st["ledger"].append({
                    "run": m2.group(1), "date": m2.group(2),
                    "state": m2.group(3), "branch": m2.group(4),
                    "what": m2.group(5),
                })
    st.setdefault("needs_human_note", "")
    return st


def _header_lines(st: dict) -> list[str]:
    return [
        f"- **state:** {st['state']}",
        f"- **run:** {st['run']}",
        f"- **last_dream:** {st['last_dream']}",
        f"- **branch:** {st['branch']}",
        f"- **proposal:** {st['proposal']}",
    ]


def write_state(st: dict) -> None:
    lines = [
        "# Dreaming state — Project 12 (The Dreaming Loop)",
        "",
        "The single source of truth for the dreaming loop. `dream.py` reads the",
        "header below to know where the last dream stopped, and rewrites it at",
        "the end of each beat. **Rule changes never happen in this file** — they",
        "live on a `claude/dream-<run>` branch awaiting a human merge; this file",
        "only records that the branch was proposed.",
        "",
        "## Header (machine-read; `- **key:** value` on the first lines)",
        "",
    ] + _header_lines(st) + ["", PROSE, "", "## Dream ledger", "",
                             "| Run | Date | State | Branch | What was proposed |",
                             "|-----|------|-------|--------|-------------------|"]
    for row in st["ledger"]:
        lines.append(f"| {row['run']} | {row['date']} | {row['state']} | "
                     f"{row['branch']} | {row['what']} |")
    lines.append("")
    STATE_MD.write_text("\n".join(lines), encoding="utf-8")


# --------------------------------------------------------------------------- #
# git / snapshot / headless-agent helpers
# --------------------------------------------------------------------------- #

def git(args: list[str], cwd: Path = REPO_ROOT) -> str:
    r = subprocess.run(["git", "-C", str(cwd)] + args,
                       capture_output=True, text=True, encoding="utf-8",
                       errors="replace")
    return (r.stdout or "").strip()


def working_tree_clean() -> tuple[bool, str]:
    dirty = git(["status", "--porcelain"])
    if dirty:
        return False, dirty
    return True, ""


def find_claude() -> str:
    p = shutil.which("claude")
    if not p:
        sys.exit("dream.py: cannot find the `claude` CLI on PATH")
    return p


def run_agent(claude: str, prompt: str, out_json: Path, cwd: Path,
              allowed: str) -> dict:
    """Run one headless `claude -p` child; persist JSON + stderr.

    The prompt travels on STDIN, not as an argv element: prompts are long and
    full of embedded double quotes, and Python's Windows argv quoting mangles
    them so the child would see an empty prompt ("Input must be provided...").
    """
    cmd = [claude, "-p", "--output-format", "json",
           "--permission-mode", "acceptEdits",
           "--no-session-persistence",
           "--allowedTools", allowed]
    stderr_path = out_json.with_suffix(".stderr")
    try:
        proc = subprocess.run(cmd, input=prompt, capture_output=True,
                              text=True, encoding="utf-8", errors="replace",
                              timeout=1200, cwd=str(cwd), env=ENV)
    except subprocess.TimeoutExpired:
        return {"ok": False, "text": "", "usage": None,
                "err": "timed out after 1200s"}
    out_json.write_text(proc.stdout or "", encoding="utf-8")
    stderr_path.write_text(proc.stderr or "", encoding="utf-8")
    try:
        j = json.loads(proc.stdout) if proc.stdout.strip() else {}
    except json.JSONDecodeError as e:
        return {"ok": False, "text": proc.stdout, "usage": None,
                "err": f"child did not return JSON: {e}"}
    text = j.get("result") or ""
    usage = j.get("usage") or {}
    return {
        "ok": not j.get("is_error", False) and bool(text),
        "text": text,
        "usage": {"input": usage.get("input_tokens", 0),
                  "output": usage.get("output_tokens", 0),
                  "cache_read": usage.get("cache_read_input_tokens", 0)},
        "err": "",
    }


def make_snapshot() -> Path:
    """Materialise HEAD into a throwaway dir under .loop12-beats (git-ignored,
    INSIDE the trusted repo tree so a headless child never stalls on the
    folder-trust prompt); return the beat dir (snapshot is <dir>/snapshot)."""
    BEATS_DIR.mkdir(exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix="dream-", dir=str(BEATS_DIR)))
    snap = tmp / "snapshot"
    snap.mkdir()
    arc = subprocess.run(["git", "-C", str(REPO_ROOT), "archive", "--format=tar",
                          "HEAD"], capture_output=True)
    if arc.returncode != 0:
        shutil.rmtree(tmp, ignore_errors=True)
        sys.exit("dream.py: git archive HEAD failed: "
                 + arc.stderr.decode("utf-8", "replace"))
    with tarfile.open(fileobj=io.BytesIO(arc.stdout), mode="r:") as tar:
        tar.extractall(snap)
    return tmp


# --------------------------------------------------------------------------- #
# scan plumbing
# --------------------------------------------------------------------------- #

def run_scan(after: str, until: str) -> dict:
    r = subprocess.run(
        [sys.executable, str(SCAN_PY), "--loop-root", str(LOOPPROJECTS),
         "--extra", str(OBSERVED), "--from", after, "--until", until, "--json"],
        capture_output=True, text=True, encoding="utf-8", errors="replace",
        timeout=120)
    if r.returncode != 0:
        raise RuntimeError("scan.py failed: " + (r.stderr or r.stdout)[:500])
    return json.loads(r.stdout)


# --------------------------------------------------------------------------- #
# usage / cost / bookkeeping
# --------------------------------------------------------------------------- #

def record_usage(run: int, date: str, phase: str, attempt: int, usage,
                 result: str) -> None:
    if not USAGE_CSV.exists():
        USAGE_CSV.write_text(
            "run,date,phase,attempt,input_tokens,output_tokens,cache_read,result\n",
            encoding="utf-8")
    u = usage or {}
    with open(USAGE_CSV, "a", encoding="utf-8") as f:
        f.write(f"{run},{date},{phase},{attempt},{u.get('input', 0)},"
                f"{u.get('output', 0)},{u.get('cache_read', 0)},{result}\n")


def cost_summary() -> tuple[list, int, int, int, int]:
    rows = []
    if USAGE_CSV.exists():
        for line in USAGE_CSV.read_text(encoding="utf-8").splitlines()[1:]:
            parts = line.split(",")
            if len(parts) == 8:
                rows.append(parts)
    tot = {"input": 0, "output": 0, "cache": 0, "runs": 0}
    for r in rows:
        tot["input"] += int(r[4]); tot["output"] += int(r[5])
        tot["cache"] += int(r[6]); tot["runs"] += 1
    return rows, tot["input"], tot["output"], tot["cache"], tot["runs"]


def render_cost() -> str:
    rows, ti, to, tc, n = cost_summary()
    beats = {}
    for r in rows:
        beats.setdefault(r[0], []).append(r)
    body = [f"| Beat | Date | Input | Output | Cache-read | Agent runs |",
            "|------|------|-------|--------|------------|------------|"]
    for b in sorted(beats):
        rs = beats[b]
        body.append(f"| {b} | {rs[0][1]} | {sum(int(x[4]) for x in rs):,} | "
                    f"{sum(int(x[5]) for x in rs):,} | "
                    f"{sum(int(x[6]) for x in rs):,} | {len(rs)} |")
    return (f"# Cost of the dreaming loop — measured, not guessed\n\n"
            f"Each beat runs two fresh headless Claude agents (Dreamer + "
            f"Checker) whose token usage is captured from each `claude -p` "
            f"run JSON (see `runs/`). Numbers are **measured**, not modelled.\n\n"
            f"## Measured tokens per beat\n\n" + "\n".join(body) +
            f"\n\nTotals over {len(beats)} beat(s): **{ti:,} input + {to:,} "
            f"output tokens**; {n} agent runs.\n\n"
            f"Dollars = tokens × provider $/MTok / 1,000,000. The dominant "
            f"term is the per-invocation harness overhead, not the loop's own "
            f"content. This machine runs the loop's backend "
            f"(`ANTHROPIC_MODEL=deepseek-v4-flash`), so substitute that "
            f"provider's $/MTok for a real figure.\n")


def render_progress(st: dict) -> str:
    last = st["ledger"][-1] if st["ledger"] else None
    header = (f"# Progress — Project 12 (The Dreaming Loop)\n\n"
              f"The meta-loop: it dreams over the other loops' dated logs, "
              f"finds a failure/correction that appears more than once, and "
              f"proposes the smallest rule/skill improvement (plus one "
              f"deletion) on a `claude/dream-<run>` branch — never on main, "
              f"never merged without a human. This file is generated by "
              f"`dream.py`.\n\n## Last dream\n\n"
              f"- **Run:** {st['run']}\n- **Date:** {st['last_dream']}\n"
              f"- **State:** {st['state']}\n- **Branch:** {st['branch']}\n")
    if last:
        header += f"- **Proposal:** {last['what']}\n"
    header += f"\n## Needs human\n\n"
    if st["state"] == "NEEDS_HUMAN" and st.get("needs_human_note"):
        header += f"- {st['needs_human_note']}\n"
    else:
        header += "- _none — no dream is blocked on a person._\n"
    return header


def log_beat(st: dict, summary: str, result: str) -> None:
    if not LOG_MD.exists():
        LOG_MD.write_text(
            "# Loop log — Project 12 (The Dreaming Loop)\n\n"
            "| Run | Date | Result | What happened |\n"
            "|-----|------|--------|---------------|\n", encoding="utf-8")
    with open(LOG_MD, "a", encoding="utf-8") as f:
        f.write(f"| {st['run']} | {st['last_dream']} | {result} | "
                f"{summary} |\n")


# --------------------------------------------------------------------------- #
# the two agents
# --------------------------------------------------------------------------- #

def load_skill(name: str) -> str:
    return (LOOP12 / "skills" / name).read_text(encoding="utf-8")


def dreamer_prompt(run: int, scan_path: Path, proposal_path: Path,
                   attempt: int, feedback: str = "") -> str:
    skill = load_skill("dreamer-skill.md")
    prompt = (skill.replace("<scan_path>", str(scan_path))
              .replace("<proposal_path>", str(proposal_path))
              .replace("<run>", str(run)))
    if feedback:
        prompt += ("\n\n## Your previous draft FAILED the Checker\n\n"
                   "The Checker's reasons, verbatim:\n\n" + feedback +
                   "\n\nFix exactly those defects and rewrite the proposal file "
                   "(overwrite it). Keep everything the Checker accepted intact.\n")
    return prompt


def checker_prompt(scan_path: Path, proposal_path: Path) -> str:
    skill = load_skill("checker-skill.md")
    return (skill.replace("<scan_path>", str(scan_path))
            .replace("<proposal_path>", str(proposal_path)))


def parse_verdict(text: str) -> str:
    m = re.search(r"VERDICT:\s*(PASS|FAIL)", text)
    return m.group(1) if m else "FAIL"


# --------------------------------------------------------------------------- #
# proposal application (the ONLY place the repo's rules change)
# --------------------------------------------------------------------------- #

def _resolve_skills(p: str) -> Path:
    p2 = p.replace("\\", "/").rstrip("/")
    if not p2.startswith(SKILLS_REL + "/") and p2 != SKILLS_REL:
        raise ValueError(f"proposal path outside the skills corpus: {p2}")
    return REPO_ROOT / p2


def pr_markdown(draft: dict) -> str:
    pr = draft.get("pr", {})
    title = (pr.get("title") or "dream: smallest rule improvement").strip()
    body = pr.get("body") or draft.get("summary", "")
    return f"# {title}\n\n{body}\n"


def apply_proposal(draft: dict, run: int) -> str:
    """Commit the reviewed proposal to claude/dream-<run>. Returns branch name.
    Touches ONLY the skills corpus + loop12/proposals. Never main, never push."""
    rule = draft.get("rule_change", {})
    dele = draft.get("deletion", {})
    if rule.get("action") not in ("add", "edit"):
        raise ValueError("rule_change.action must be add|edit")
    rule_path = _resolve_skills(rule["path"])
    delete_path = _resolve_skills(dele["path"]) if dele.get("path") else None
    if delete_path == rule_path:
        raise ValueError("deletion targets the same file as the rule change")

    branch = f"claude/dream-{run}"
    git(["checkout", "-b", branch])
    try:
        if rule["action"] == "add":
            if rule_path.exists():
                raise ValueError(f"action=add but {rule['path']} already exists")
            rule_path.parent.mkdir(parents=True, exist_ok=True)
        else:  # edit
            if not rule_path.exists():
                raise ValueError(f"action=edit but {rule['path']} is missing")
        rule_path.write_text(rule["content"], encoding="utf-8")

        if delete_path and delete_path.exists():
            delete_path.unlink()

        props = LOOP12 / "proposals" / branch
        props.mkdir(parents=True, exist_ok=True)
        (props / "proposal.json").write_text(
            json.dumps(draft, indent=2, ensure_ascii=False), encoding="utf-8")
        pr_text = pr_markdown(draft)
        (props / "PR.md").write_text(pr_text, encoding="utf-8")
        # PR body also becomes the commit message; keep the scratch message
        # file OUTSIDE proposals/ so it never leaks into the PR's diff.
        BEATS_DIR.mkdir(exist_ok=True)
        title = pr_text.splitlines()[0].lstrip("# ").strip()
        msg_path = BEATS_DIR / f"commit-{branch}.msg"
        msg_path.write_text(f"{title}\n\n"
                            + (draft.get("pr", {}).get("body")
                               or draft.get("summary", ""))
                            + COMMIT_TRAILER + "\n", encoding="utf-8")

        git(["add", str(rule_path.relative_to(REPO_ROOT)).replace("\\", "/")])
        if delete_path:
            git(["add", "-A",
                 str(delete_path.relative_to(REPO_ROOT)).replace("\\", "/")])
        git(["add",
             str(props.relative_to(REPO_ROOT)).replace("\\", "/")])
        git(["commit", "-F", str(msg_path)])
        msg_path.unlink()
        git(["checkout", "main"])
    except BaseException:
        git(["checkout", "main"])
        git(["branch", "-D", branch])
        raise
    return branch


# --------------------------------------------------------------------------- #
# the beat
# --------------------------------------------------------------------------- #

def run_beat(claude: str, today: str, max_attempts: int) -> int:
    st = read_state()
    if st["state"] == "NEEDS_HUMAN":
        log_beat(st, "HOLD — dreaming loop is NEEDS_HUMAN: "
                     f"{st['needs_human_note'][:160]}", "HOLD")
        print(f"HOLD: state is NEEDS_HUMAN — {st['needs_human_note']}")
        return 0
    if st["branch"] not in ("—", ""):
        log_beat(st, f"HOLD — awaiting human merge of {st['branch']}", "HOLD")
        print(f"HOLD: proposal {st['branch']} is open; merge it, then --reset.")
        return 0

    clean, dirty = working_tree_clean()
    if not clean:
        print("Aborting: working tree is not clean. Commit or stash first:\n"
              + dirty)
        return 2

    after = st["last_dream"]
    if after >= today:
        print(f"Nothing newer than last dream ({after}) — already dreamed "
              f"through {after}.")
        return 0

    run = int(st["run"]) + 1
    scan = run_scan(after, today)
    run_dir = RUNS_DIR / f"dream-{run}"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "scan.json").write_text(json.dumps(scan, indent=2), encoding="utf-8")

    if not scan["clusters"]:
        # a beat can be a no-dream: nothing repeated is worth a rule
        st["run"] = run; st["last_dream"] = today
        st["state"] = "IDLE"; st["branch"] = "—"; st["proposal"] = "—"
        st["ledger"].append({"run": run, "date": today, "state": "IDLE",
                             "branch": "—",
                             "what": f"no repeat found in "
                                     f"{scan['records_in_window']} dated records"})
        write_state(st)
        PROGRESS_MD.write_text(render_progress(st), encoding="utf-8")
        COST_MD.write_text(render_cost(), encoding="utf-8")
        log_beat(st, f"no repeated failure/correction in the window "
                     f"({scan['records_in_window']} dated records)", "NO_REPEAT")
        print("No repeated failure/correction in the window — nothing to dream.")
        return 0

    # one fresh snapshot the agents work in (never the live tree)
    beat_tmp = make_snapshot()
    snap = beat_tmp / "snapshot"
    scan_json_path = beat_tmp / "scan.json"
    scan_json_path.write_text(json.dumps(scan, indent=2), encoding="utf-8")
    proposal_path = beat_tmp / "proposal.json"
    proposal_path.write_text("{}", encoding="utf-8")

    verdict = "FAIL"
    last_check = ""
    for attempt in range(1, max_attempts + 1):
        # DREAMER
        out = run_agent(claude, dreamer_prompt(run, scan_json_path,
                                               proposal_path, attempt,
                                               last_check),
                        run_dir / f"dreamer-a{attempt}.json", snap,
                        allowed="Read,Glob,Grep,Write")
        record_usage(run, today, "dreamer", attempt, out["usage"],
                     "OK" if out["ok"] else "ERR")
        try:
            draft = json.loads(proposal_path.read_text(encoding="utf-8"))
            if not draft or draft == {}:
                raise ValueError("empty proposal")
        except Exception:
            last_check = (f"The Dreamer did not write a valid proposal JSON to "
                          f"{proposal_path} (it must overwrite that file). "
                          + (out["err"] if out["err"] else ""))
            continue
        # CHECKER (fresh, read-only)
        ck = run_agent(claude, checker_prompt(scan_json_path, proposal_path),
                       run_dir / f"checker-a{attempt}.json", snap,
                       allowed="Read,Glob,Grep")
        verdict = parse_verdict(ck["text"])
        record_usage(run, today, "checker", attempt, ck["usage"], verdict)
        if verdict == "PASS":
            break
        last_check = ck["text"].strip() or "no text returned"
        print(f"  attempt {attempt}: Checker FAIL -> retrying Dreamer")

    if verdict != "PASS":
        st["state"] = "NEEDS_HUMAN"
        st["needs_human_note"] = (f"Dream {run} exhausted {max_attempts} "
                                  f"attempts. Last Checker: {last_check[:300]}")
        st["run"] = run                 # keep last_dream so a retry re-scans
        st["branch"] = "—"; st["proposal"] = "—"
        st["ledger"].append({"run": run, "date": today, "state": "NEEDS_HUMAN",
                             "branch": "—", "what": "Checker never PASSed"})
        write_state(st)
        PROGRESS_MD.write_text(render_progress(st), encoding="utf-8")
        COST_MD.write_text(render_cost(), encoding="utf-8")
        log_beat(st, "escalated — checker never PASSed", "ESCALATED")
        print(f"Escalated to NEEDS_HUMAN after {max_attempts} attempts.\n"
              f"Last Checker feedback:\n{last_check}")
        return 0

    # PASS -> apply to a claude/dream-<run> branch (never main)
    branch = apply_proposal(draft, run)
    props = LOOP12 / "proposals" / branch
    # keep a copy of the reviewed proposal on the main-side paper trail too
    (run_dir / "proposal.json").write_text(
        json.dumps(draft, indent=2, ensure_ascii=False), encoding="utf-8")
    (run_dir / "PR.md").write_text(pr_markdown(draft), encoding="utf-8")

    st["state"] = "PROPOSED"; st["run"] = run; st["last_dream"] = today
    st["branch"] = branch
    st["proposal"] = str((props / "PR.md").relative_to(LOOP12)).replace("\\", "/")
    what = (draft.get("pr", {}).get("title")
            or draft.get("repeated_failure", {}).get("theme", ""))[:160]
    st["ledger"].append({"run": run, "date": today, "state": "PROPOSED",
                         "branch": branch, "what": what})
    write_state(st)
    PROGRESS_MD.write_text(render_progress(st), encoding="utf-8")
    COST_MD.write_text(render_cost(), encoding="utf-8")
    log_beat(st, f"PROPOSED {branch} — {what}", "PROPOSED")

    print(_summary(st, draft, branch, props))
    return 0


def _summary(st: dict, draft: dict, branch: str, props: Path) -> str:
    rf = draft.get("repeated_failure", {})
    rc = draft.get("rule_change", {})
    dl = draft.get("deletion", {})
    pr = draft.get("pr", {})
    occ = rf.get("occurrences", [])
    s = []
    s.append("=" * 70)
    s.append(f"DREAMING BEAT {st['run']} ({st['last_dream']}) — PROPOSAL ON A "
             f"BRANCH")
    s.append("=" * 70)
    s.append(f"Repeated failure  : {rf.get('theme')}")
    s.append(f"  occurrences     : {len(occ)} dated records — " +
             ", ".join(f'{o.get("date")} {o.get("run")} {o.get("file")}:{o.get("line")}'
                       for o in occ))
    s.append(f"  how many times  : {rf.get('how_many_occurrences')}")
    s.append(f"Rule change       : {rc.get('action')} "
             f"{rc.get('path')} ({len(rc.get('content', ''))} chars)")
    s.append(f"Deletion          : {dl.get('path')} — {dl.get('reason')}")
    s.append("")
    s.append(f"The branch `{branch}` holds the rule change + PR body.")
    s.append("Rule files on `main` are UNCHANGED. Merge is a human step.")
    s.append("")
    s.append("Review + open the PR (local claude/ branch, never pushed):")
    s.append(f"  git push -u origin {branch}")
    s.append(f"  gh pr create --base main --head {branch} "
             f"--title {pr.get('title','')!r} --body-file "
             f"{LOOP12_REL}/proposals/{branch}/PR.md")
    s.append("")
    s.append("Commit the dreaming-loop bookkeeping on main (state/log/progress/"
             "cost/runs):")
    s.append(f"  git add {LOOP12_REL}")
    s.append(f"  git commit -m \"loop12: dream {st['run']} — {what_for(st, pr)}\"")
    s.append("")
    s.append("PR body preview (proposals/{}/PR.md):".format(branch))
    s.append(("-" * 70))
    s.append((pr.get("body") or "")[:1800])
    s.append(("-" * 70))
    return "\n".join(s)


def what_for(st: dict, pr: dict) -> str:
    t = (pr.get("title") or "propose smallest rule improvement")
    return t[:100]


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def main() -> int:
    ap = argparse.ArgumentParser(description="Dreaming-Loop orchestrator")
    ap.add_argument("--init", action="store_true", help="scaffold loop12 files")
    ap.add_argument("--date", help="run one dreaming beat for this YYYY-MM-DD")
    ap.add_argument("--check", action="store_true", help="run the scan only")
    ap.add_argument("--show", action="store_true", help="print the dreaming state")
    ap.add_argument("--reset", action="store_true", help="clear NEEDS_HUMAN")
    ap.add_argument("--max-attempts", type=int, default=MAX_ATTEMPTS)
    args = ap.parse_args()

    if args.init:
        RUNS_DIR.mkdir(exist_ok=True)
        if not STATE_MD.exists():
            write_state(STATE_DEFAULTS)
        for p, txt in [(LOG_MD, None), (PROGRESS_MD, None), (COST_MD, None)]:
            if not p.exists():
                p.write_text("", encoding="utf-8")
        if not PROGRESS_MD.exists() or PROGRESS_MD.read_text().strip() == "":
            PROGRESS_MD.write_text(render_progress(read_state()), encoding="utf-8")
        if not LOG_MD.exists() or LOG_MD.read_text().strip() == "":
            LOG_MD.write_text(
                "# Loop log — Project 12 (The Dreaming Loop)\n\n"
                "| Run | Date | Result | What happened |\n"
                "|-----|------|--------|---------------|\n", encoding="utf-8")
        COST_MD.write_text(render_cost(), encoding="utf-8")
        print("loop12 scaffold ready. Next: python loop12/dream.py --date "
              "YYYY-MM-DD")
        return 0

    if args.show:
        st = read_state()
        print(json.dumps({k: v for k, v in st.items() if k != "ledger"},
                         indent=2, ensure_ascii=False))
        for row in st["ledger"]:
            print(f'  dream {row["run"]} {row["date"]} [{row["state"]}] '
                  f'{row["branch"]}: {row["what"]}')
        return 0

    if args.reset:
        st = read_state()
        st["state"] = "IDLE"; st["branch"] = "—"; st["proposal"] = "—"
        st["needs_human_note"] = ""
        write_state(st)
        print("reset -> IDLE")
        return 0

    if args.check:
        st = read_state()
        scan = run_scan(st["last_dream"], args.date or str(_date.today()))
        print(json.dumps(scan, indent=2, ensure_ascii=False))
        return 0

    if args.date:
        return run_beat(find_claude(), args.date, args.max_attempts)

    ap.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
